### ISSUE TITLE
Implement a tree with a branch width of 4

### ISSUE THREAD

**Issue by krl** [dusk-network/kelvin#32]
For zk-proof reasons, we need a datastructure that is pretty narrow.

**Comment by CPerezz** [comment]
@krl Maybe I was not clear enough on the call we had.

The idea is to be able to construct a tree with a custom ARITY by sending this ARITY as parameter.

So for example on the kelvin-hamt crate, have something like:
```rust
let hamt = HAMT::new(4usize);
```

And on this way, obtain a tree with the `ARITY` you want. I think that this will directly imply that the `Branch` structure will have a length of `ARITY` for each one of it's levels. Which is the goal.

**Comment by CPerezz** [comment]
After discussing it in the call, I think it's better to wait until we have the daily tomorrow and we consider if it's reasonable to go for this issue or not.

So will leave it in Q/A until we decide what to do.

**Comment by CPerezz** [comment]
Finally we had a conversation where the functionalities that this tree should provide were defined on a high-level manner. 

SO the requirements for this tree can be found here: https://github.com/dusk-network/documentation/blob/master/DERs/smart-contract-storage-solution.md
