### ISSUE TITLE
Generate already filled trees. 

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/kelvin#35]
The problem is, that now kelvin trees have variable height (which makes sense) since the length grows while you fill the tree.
But this carries a problem. The proofs have variable length depending on the length of the kelvin tree that stores the leaves you're proving.

To make an example:
Let's suppose that I fill the tree with 1024 Scalar.
When I want to elaborate a proof for the 0th or the 657th, since they are stored at some height the circuit size is one, but when i prove the 1023rd leaf, our circuit size is indeed bigger.

To solve this, @toghrulmaharramov suggested the following:
> Trees have to be initialized with a fixed size per instantiation. So if a whitelist tree is supposed to have 2^16 leaves, it should be initialized that way and remain forever.

This might affect the performance, but it's needed since otherwise we can't preprocess our PLONK circuits and that's a really big regression on the overall protocol.

WTDY @krl ? 
Which implications would this have? Also, is it possible to force this logic for the Narrow-Tree structures? Since these are the only trees on where we need this behaviour.

This is not directly blocking https://github.com/dusk-network/Poseidon252/issues/7 but we need to solve that. 

Since it is indeed a blocker for: https://github.com/dusk-network/dusk-blindbid/issues/3

**Comment by krl** [comment]
deprecated by #37
