### ISSUE TITLE
Integrate kelvin with canonical

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/kelvin#50]
We need kelvin to be fully integrated with Canonical. 

Together with #48 this will allow the handling of Smart Contracts much easier.

**Comment by CPerezz** [comment]
Once #49 is closed, @krl should be assigned to this.

**Comment by krl** [comment]
Currently tracking down a bug with encoding/decoding found porting the HAMT implementation.

**Comment by krl** [comment]
Deprecated due to microkelvin
